### ISSUE TITLE
Can you provide a demo？

### ISSUE THREAD

**Issue by pbzyy** [bilalyasin1616/ebaysharp#1]
Can you provide a demo？

Thanks.

**Comment by bilalyasin1616** [comment]
Sorry I haven't been able to document the project yet due to time limitation. But I will provide some code sample with more details as soon as I get time.

**Comment by pbzyy** [comment]
I'm looking forward to your demo. While you some time, then you update,thanks

**Comment by pbzyy** [comment]
I have a suggestion that you can add Polly, Because resharp request may be a excetion.

**Comment by pbzyy** [comment]
![image](https://user-images.githubusercontent.com/4442711/125724012-b670bf79-3d96-4d14-a499-144c0c420825.png)
![image](https://user-images.githubusercontent.com/4442711/125724038-eeeb729a-07ec-4c07-9429-949258d5a5c3.png)

**Comment by bilalyasin1616** [comment]
Hi @pbzyy 
I haven't been able to get back to it sorry. I will write the document tonight. Maybe after that you can add Polly to it and create a pull request. I will review and if it makes sense to me I will accept the PR. Thanks

**Comment by siasty** [comment]
I also ask for a sample.

**Comment by bilalyasin1616** [comment]
@pbzyy @siasty I have added very basic guide for this library will complete it soon. If you guys have any questions let me know. Thanks

**Comment by siasty** [comment]
Hi, do you have any way to download **Authorization code grant** from httpclient ?
at the moment i am using gui and logging in via chromedriver 
![obraz](https://user-images.githubusercontent.com/39690589/126700396-9bf9795b-0f54-4c40-acd2-6867c8ea6941.png)
but i would prefer to get by httpclient , the target server will not have a desktop 
do you have any solution ?

**Comment by bilalyasin1616** [comment]
@siasty yes you need to register as dev on Ebay developer portal, generate redirect url, redirect user to that url for consent, create an API end point that will receive the return call, grab the code from request data and pass it to library function for getting access codes.
Follow following section
https://github.com/bilalyasin1616/ebaysharp#getting-access-tokens
