### ISSUE TITLE
scope is invalid

### ISSUE THREAD

**Issue by siasty** [bilalyasin1616/ebaysharp#3]
Hi, when i use method GetApplicationTokenAsyc() i have error "The requested scope is invalid, unknown, malformed, or exceeds the scope granted to the client. 
i check code you have hardcode in parametr scope. 

![obraz](https://user-images.githubusercontent.com/39690589/128025599-ecebc4bc-be08-45ca-a514-7d78973e17c6.png)

Can you change code to geting this parametr from ClientToken

**Comment by bilalyasin1616** [comment]
@siasty thanks for pointing out, my bad. Just applied the fix in 1.0.8 you can update.

**Comment by siasty** [comment]
thanks, for a quick response.

are you planning service for eBay Marketplace Account Deletion?

**Comment by bilalyasin1616** [comment]
No problem.

Might do in near future but due to lack of time can't give a exact timeline sorry.

**Comment by siasty** [comment]
I understand perfectly.

**Comment by bilalyasin1616** [comment]
Thanks, closing this issue.
